create layout and style specifically for instructor insights
mitodl/ocw-course-hugo-theme pull request #20
Opened 2021-01-20 22:06 UTC by gumaerc

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

2021-01-21 22:40 UTC, noisecapella requested changes

2021-01-21 22:40 UTC, noisecapella commented on package.json
> +    "start:webpack": "webpack-dev-server --config assets/webpack/webpack.dev.js --hot --host 0.0.0.0",
Should there be a `start` command too?

2021-01-21 23:04 UTC, gumaerc commented on package.json
> +    "start:webpack": "webpack-dev-server --config assets/webpack/webpack.dev.js --hot --host 0.0.0.0",
yes, my bad

2021-01-22 17:48 UTC, noisecapella commented
I'm seeing this error when running the hugo command:

    ERROR 2021/01/22 12:46:27 render of "page" failed: execute of template failed: template: course/course_section.html:8:7: executing "course/course_section.html" at <partialCached "mobile_course_info.html" . .Params.course_id>: error calling partialCached: execute of template failed: template: partials/mobile_course_info.html:5:5: executing "partials/mobile_course_info.html" at <partial "course_info.html" (dict "context" . "inPanel" true)>: error calling partial: "/home/george/Projects/ocw-course-hugo-theme/layouts/partials/course_info.html:19:35": execute of template failed: template: partials/course_info.html:19:35: executing "partials/course_info.html" at <len $courseData.instructors>: error calling len: reflect: call of reflect.Value.Type on zero Value
    ERROR 2021/01/22 12:46:27 render of "page" failed: execute of template failed: template: course/course_section.html:8:7: executing "course/course_section.html" at <partialCached "mobile_course_info.html" . .Params.course_id>: error calling partialCached: execute of template failed: template: partials/mobile_course_info.html:5:5: executing "partials/mobile_course_info.html" at <partial "course_info.html" (dict "context" . "inPanel" true)>: error calling partial: "/home/george/Projects/ocw-course-hugo-theme/layouts/partials/course_info.html:19:35": execute of template failed: template: partials/course_info.html:19:35: executing "partials/course_info.html" at <len $courseData.instructors>: error calling len: reflect: call of reflect.Value.Type on zero Value
    ERROR 2021/01/22 12:46:27 render of "page" failed: execute of template failed: template: course/pdf.html:8:7: executing "course/pdf.html" at <partialCached "mobile_course_info.html" . .Params.course_id>: error calling partialCached: execute of template failed: template: partials/mobile_course_info.html:5:5: executing "partials/mobile_course_info.html" at <partial "course_info.html" (dict "context" . "inPanel" true)>: error calling partial: "/home/george/Projects/ocw-course-hugo-theme/layouts/partials/course_info.html:19:35": execute of template failed: template: partials/course_info.html:19:35: executing "partials/course_info.html" at <len $courseData.instructors>: error calling len: reflect: call of reflect.Value.Type on zero Value
    ERROR 2021/01/22 12:46:27 render of "page" failed: execute of template failed: template: course/pdf.html:8:7: executing "course/pdf.html" at <partialCached "mobile_course_info.html" . .Params.course_id>: error calling partialCached: execute of template failed: template: partials/mobile_course_info.html:5:5: executing "partials/mobile_course_info.html" at <partial "course_info.html" (dict "context" . "inPanel" true)>: error calling partial: "/home/george/Projects/ocw-course-hugo-theme/layouts/partials/course_info.html:19:35": execute of template failed: template: partials/course_info.html:19:35: executing "partials/course_info.html" at <len $courseData.instructors>: error calling len: reflect: call of reflect.Value.Type on zero Value
    Built in 149 ms
    Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: course/course_section.html:8:7: executing "course/course_section.html" at <partialCached "mobile_course_info.html" . .Params.course_id>: error calling partialCached: execute of template failed: template: partials/mobile_course_info.html:5:5: executing "partials/mobile_course_info.html" at <partial "course_info.html" (dict "context" . "inPanel" true)>: error calling partial: "/home/george/Projects/ocw-course-hugo-theme/layouts/partials/course_info.html:19:35": execute of template failed: template: partials/course_info.html:19:35: executing "partials/course_info.html" at <len $courseData.instructors>: error calling len: reflect: call of reflect.Value.Type on zero Value

2021-01-22 17:59 UTC, gumaerc commented
Yea, sorry I didn't clarify about that part.

2021-01-22 18:01 UTC, noisecapella requested changes

2021-01-22 18:01 UTC, noisecapella commented on assets/webpack/webpack.dev.js
>      hot: true,
Can we also add `disableHostCheck: true` here to work around cross origin errors on dev servers?

2021-01-22 18:04 UTC, noisecapella commented
Functionality works great, just the one suggestion

2021-01-22 18:13 UTC, gumaerc commented
@noisecapella all set

2021-01-22 18:14 UTC, noisecapella approved these changes

2021-01-22 18:16 UTC, merged